openapi: "3.0.0"
info:
  description: ""
  version: 1.0.0
  title: National Grid Carbon Intensity
  termsOfService: "https://carbonintensity.org.uk/terms"
  contact:
    email: "api@carbonintensity.org.uk"
  license:
    name: "CC BY 4.0"
    url: "https://creativecommons.org/licenses/by/4.0/"
externalDocs:
  description: Documentation & methodology
  url: http://carbonintensity.org.uk/methodology
servers:
- url: https://9zot0ysfl7.execute-api.eu-west-2.amazonaws.com/v0
  description: Production API server
tags:
- name: intensity
  description: Forecast and actual carbon intensity data
paths:
  /intensity/date:
    get:
      tags:
      - intensity
      summary: Get national carbon intensity data for today
      operationId: dateToday
      produces:
      - application/json
      responses:
        $ref: "#/components/responses/Intensities"
  /intensity/date/{date}:
    get:
      tags:
      - intensity
      summary: Get national carbon intensity data for a single day
      operationId: settlementDate
      parameters:
      - name: "date"
        in: "path"
        description: "Date in YYYY-MM-DD format, e.g. 2017-08-23"
        required: true
        type: string
        format: date
      produces:
      - application/json
      responses:
        $ref: "#/components/responses/Intensities"
components:
  responses:
    Intensities:
      200:
        description: Success
        schema:
          $ref: "#/definitions/Intensities"
      403:
        description: Access forbidden
      404:
        description: Date not found
definitions:
  Intensities:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/Intensity"
  Intensity:
    type: object
    properties:
      from:
        type: string
        format: datetime
        example: "2017-09-12 00:30"
        description: The beginning of the half hour settlement period. In the format YYYY-MM-DD HH:MM and is the local time so either GMT(+0) or BST(+1) depending on Daylight Savings Time.
      to:
        type: string
        format: datetime
        example: "2017-09-12 01:00"
        description: The end of the half hour settlement period. In the format YYYY-MM-DD HH:MM and is the local time so either GMT(+0) or BST(+1) depending on Daylight Savings Time.
      intensity:
        type: object
        properties:
          actual:
            type: number
            format: float
            example: null
            description: The average outturn CO2 emission intensity or carbon intensity for the half hour settlement period with units gCO2-eq/kWh. For future values, this will be null.
          forecast:
            type: number
            format: float
            example: 137.1
            description: The average forecast CO2 emission intensity or carbon intensity for the half hour settlement period with units gCO2-eq/kWh.
          index:
            type: string
            description: How high the emission value is, compared to average. Can be one of "very high", "high", "moderate", "low", or "very low".
            example: "moderate"
