openapi: "3.0.0"
info:
  description: ""
  version: 1.0.0
  title: National Grid Carbon Intensity
  termsOfService: "https://carbonintensity.org.uk/terms"
  contact:
    email: "api@carbonintensity.org.uk"
  license:
    name: "CC BY 4.0"
    url: "https://creativecommons.org/licenses/by/4.0/"
externalDocs:
  description: Documentation & methodology
  url: http://carbonintensity.org.uk/methodology
servers:
- url: https://9zot0ysfl7.execute-api.eu-west-2.amazonaws.com/v0
  description: Production API server
tags:
- name: Intensity
  description: Forecast and actual carbon intensity data
- name: Statistics
  description: Intensity statistics (min, max, average) over requested periods
paths:
  /intensity/date:
    get:
      tags:
      - Intensity
      summary: Get national carbon intensity data for today
      operationId: getIntensityForToday
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
  /intensity/date/{date}:
    get:
      tags:
      - Intensity
      summary: Get national carbon intensity data for a single day
      operationId: getIntensityForDate
      parameters:
      - name: date
        in: path
        description: "Date in YYYY-MM-DD format, e.g. 2017-08-23"
        required: true
        schema:
          type: string
          format: date
          example: "2017-08-23"
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/stats/{from}/{to}:
    get:
      tags:
      - Statistics
      summary: Get emission statistics for a requested period
      operationId: getStatsFromTo
      parameters:
      - name: from
        in: path
        description: "Start date and time in ISO8601 format, e.g. 2017-09-01T00:00Z"
        required: true
        schema:
          type: string
          format: datetime
          example: "2017-09-01T00:00Z"
      - name: to
        in: path
        description: "End date and time in ISO8601 format, e.g. 2017-09-02T12:00Z"
        required: true
        schema:
          type: string
          format: datetime
          example: "2017-09-02T12:00Z"
      responses:
        200: 
          $ref: "#/components/responses/Statistics"
        400: 
          $ref: "#/components/responses/BadDateFormat"
components:
  responses:
    Intensities:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/IntensityArray"
    Statistics:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StatisticArray"
    BadDateFormat:
      description: Incorrect date/time format supplied, or end may be before start.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"
    NotFound:
      description: Date not found
  schemas:
    IntensityArray:
      type: object 
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/IntensityValue"
    IntensityValue:
      type: object
      properties:
        from:
          type: string
          format: datetime
          example: "2017-09-12 00:30"
          description: The beginning of the half hour settlement period. In the format YYYY-MM-DD HH:MM and is the local time so either GMT(+0) or BST(+1) depending on Daylight Savings Time.
        to:
          type: string
          format: datetime
          example: "2017-09-12 01:00"
          description: The end of the half hour settlement period. In the format YYYY-MM-DD HH:MM and is the local time so either GMT(+0) or BST(+1) depending on Daylight Savings Time.
        intensity:
          type: object
          properties:
            actual:
              type: number
              format: float
              example: null
              description: The average outturn CO2 emission intensity or carbon intensity for the half hour settlement period with units gCO2-eq/kWh. For future values, this will be null.
            forecast:
              type: number
              format: float
              example: 137.1
              description: The average forecast CO2 emission intensity or carbon intensity for the half hour settlement period with units gCO2-eq/kWh.
            index:
              type: string
              description: How high the emission value is, compared to average. Can be one of "very high", "high", "moderate", "low", or "very low".
              example: "moderate"
    StatisticArray:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/StatisticValue'
    StatisticValue:
      type: object
      properties:
        from:
          type: string
          format: datetime
          example: '2017-09-12 00:30'
          description: The beginning of the requested period. In the format YYYY-MM-DD HH:MM.
        to:
          type: string
          format: datetime
          example: '2017-09-12 01:00'
          description: The beginning of the requested period. In the format YYYY-MM-DD HH:MM.
        intensity:
          type: object
          properties:
            max:
              type: number
              format: float
              example: 292
              description: The maxmimum CO2 emission intensity during the requested period in units of gCO2-eq/kWh. Future periods will use forecast data, past periods will use actual.
            average:
              type: number
              format: float
              example: 218
              description: The average CO2 emission intensity during the requested period in units of gCO2-eq/kWh. Future periods will use forecast data, past periods will use actual.
            min:
              type: number
              format: float
              example: 143
              description: The minimum CO2 emission intensity during the requested period in units of gCO2-eq/kWh. Future periods will use forecast data, past periods will use actual.
            index:
              type: string
              description: How high the average value in this period is, compared to a longer-term average. Can be one of "very high", "high", "moderate", "low", or "very low".
              example: moderate
    ErrorMessage:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: "400 Bad Request"
              description: the HTTP error code produced
            message:
              type: string
              example: "Please enter a valid start and end datetime in ISO8601 format 'YYYY-MM-DDThh:mm'"
