openapi: "3.0.0"
info:
  description: "This is the official Carbon Intensity API for Great Britain developed by National Grid. You can find out more about carbon intensity at [https://carbonintensity.org.uk](https://carbonintensity.org.uk/).<p>**Summary**</p> National Grid’s Carbon Intensity API provides an indicative trend of carbon intensity of the electricity system in Great Britain (GB) up to 48-hours ahead of real-time. It provides programmatic and timely access to both forecast and estimated actual carbon intensity data. The carbon intensity forecast includes CO2 emissions related to electricity generation only. The forecast includes CO2 emissions from all large metered power stations, interconnector imports, transmission and distribution losses, and accounts for national electricity demand, embedded wind and solar generation."
  version: 1.0.0
  title: "Carbon Intensity API"
  termsOfService: "https://carbonintensity.org.uk/terms"
  contact:
    email: "Alasdair.Bruce@nationalgrid.com"
  license:
    name: "CC-BY-4.0"
    url: "https://creativecommons.org/licenses/by/4.0/"
externalDocs:
  description: Documentation & methodology
  url: http://carbonintensity.org.uk/
servers:
- url: https://k1nehbcl85.execute-api.eu-west-2.amazonaws.com/v1
  description: Production API server
tags:
- name: Intensity
  description: Forecast and actual carbon intensity data
- name: Statistics
  description: Intensity statistics (min, max, average) over requested periods
paths:
  /intensity:
    get:
      tags:
      - Intensity
      summary: "Get carbon intensity data for current half hour"
      description: "Get carbon intensity data for current half hour settlement period. All times provided in UTC."
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
  /intensity/date:
    get:
      tags:
      - Intensity
      summary: Get carbon intensity data for today
      description: "Get carbon intensity data for today. All times provided in UTC."
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
  /intensity/date/{date}:
    get:
      tags:
      - Intensity
      summary: Get carbon intensity data for a specific date
      description: "Get carbon intensity data for a specific date. All times provided in UTC."
      parameters:
      - name: date
        in: path
        description: "Date in YYYY-MM-DD format, e.g. 2017-08-23"
        required: true
        schema:
          type: string
          format: date
          example: "2017-08-23"
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/date/{date}/{period}:
    get:
      tags:
      - Intensity
      summary: "Get carbon intensity data for specific date and period"
      description: "Get carbon intensity data for a specific date and half hour settlement period. All times provided in UTC."
      parameters:
      - name: "date"
        in: "path"
        description: "Date in YYYY-MM-DD format e.g. 2017-08-25"
        required: true
        schema:
          type: string
          format: date
          example: "2017-08-23"
      - name: "period"
        in: "path"
        description: "Half hour settlement period between 1-48 e.g. 42"
        required: true
        schema:
          type: integer
          example: 42
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/{from}:
    get:
      tags:
      - Intensity
      summary: "Get carbon intensity data for specific half hour period"
      description: "Get carbon intensity data for specific half hour period. All times provided in UTC."
      parameters:
      - name: "from"
        in: "path"
        description: "Datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. 2017-08-25T12:35Z"
        required: true
        schema:
          type: "string"
          example: "2017-08-25T12:35Z"
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/{from}/fw24h:
    get:
      tags:
      - Intensity
      summary: "Get carbon intensity data 24hrs forwards from specific datetime"
      description: "Get carbon intensity data between the {from} datetime specified and 24hrs before. All times provided in UTC."
      parameters:
      - name: "from"
        in: "path"
        description: "Start datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. 2017-08-25T12:35Z"
        required: true
        schema:
          type: "string"
          example: "2017-08-25T12:35Z"
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/{from}/fw48h:
    get:
      tags:
      - Intensity
      summary: "Get carbon intensity data 48hrs forwards from specific datetime"
      description: "Get carbon intensity data between the {from} datetime specified and 48hrs after. All times provided in UTC."
      parameters:
      - name: "from"
        in: "path"
        description: "Start datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. 2017-08-25T12:35Z"
        required: true
        schema:
          type: "string"
          example: "2017-08-25T12:35Z"
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/{from}/pt24h:
    get:
      tags:
      - Intensity
      summary: "Get carbon intensity data 24hrs in the past of a specific datetime"
      description: "Get carbon intensity data between the {from} datetime specified and 24hrs before. All times provided in UTC."
      parameters:
      - name: "from"
        in: "path"
        description: "Start datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. 2017-08-25T12:35Z"
        required: true
        schema:
          type: "string"
          example: "2017-08-25T12:35Z"
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/{from}/{to}:
    get:
      tags:
      - Intensity
      summary: "Get carbon intensity data between from and to datetime"
      description: "Get carbon intensity data between the {from} and {to} datetimes. The maximum date range is limited to 30 days. All times provided in UTC."
      parameters:
      - name: "from"
        in: "path"
        description: "Start datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. 2017-08-25T12:35Z"
        required: true
        schema:
          type: "string"
          example: "2017-08-25T12:35Z"
      - name: "to"
        in: "path"
        description: "End datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. 2017-08-25T12:35Z"
        required: true
        schema:
          type: "string"
          example: "2017-08-25T12:35Z"
      responses:
        200: 
          $ref: "#/components/responses/Intensities"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/stats/{from}/{to}:
    get:
      tags:
      - Statistics
      summary: Get emission statistics for a requested period
      operationId: getStatsFromTo
      parameters:
      - name: from
        in: path
        description: "Start date and time in ISO8601 format, e.g. 2017-09-01T00:00Z"
        required: true
        schema:
          type: string
          format: datetime
          example: "2017-09-01T00:00Z"
      - name: to
        in: path
        description: "End date and time in ISO8601 format, e.g. 2017-09-02T12:00Z"
        required: true
        schema:
          type: string
          format: datetime
          example: "2017-09-02T12:00Z"
      responses:
        200: 
          $ref: "#/components/responses/Statistics"
        400: 
          $ref: "#/components/responses/BadDateFormat"
  /intensity/stats/{from}/{to}/{block}:
    get:
      tags:
      - Statistics
      summary: "Get block average carbon intensity statistics between from and to datetime"
      description: "Get block average carbon intensity statistics (average, max, mean) between from and to datetime. The maximum date range is limited to 30 days. The maximum block length is 24 hours. All times provided in UTC."
      parameters:
      - name: "from"
        in: "path"
        description: "Start datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. '2017-08-25T12:35Z'"
        required: true
        schema:
          type: string
          format: datetime
          example: "2017-09-02T12:00Z"
      - name: "to"
        in: "path"
        description: "End datetime in in ISO8601 format YYYY-MM-DDThh:mmZ e.g. '2017-08-26T17:00Z'"
        required: true
        schema:
          type: string
          format: datetime
          example: "2017-09-02T12:00Z"
      - name: "block"
        in: "path"
        description: "Block length in hours i.e. a block length of 2 hrs over a 24 hr period returns 12 items with the average, max, min for each 2 hr block e.g. 2017-08-26T17:00Z/2017-08-27T17:00Z/2"
        required: true
        schema:
          type: integer
      responses:
        200: 
          $ref: "#/components/responses/Statistics"
        400: 
          $ref: "#/components/responses/BadDateFormat"
components:
  responses:
    Intensities:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/IntensityArray"
    Statistics:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StatisticArray"
    BadDateFormat:
      description: Incorrect date/time format supplied, or end may be before start.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"
    NotFound:
      description: Date not found
  schemas:
    IntensityArray:
      type: object 
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/IntensityValue"
    IntensityValue:
      type: object
      properties:
        from:
          type: string
          format: datetime
          example: "2017-09-12 00:30"
          description: The beginning of the half hour settlement period. In the format YYYY-MM-DD HH:MM and is the local time so either GMT(+0) or BST(+1) depending on Daylight Savings Time.
        to:
          type: string
          format: datetime
          example: "2017-09-12 01:00"
          description: The end of the half hour settlement period. In the format YYYY-MM-DD HH:MM and is the local time so either GMT(+0) or BST(+1) depending on Daylight Savings Time.
        intensity:
          type: object
          properties:
            actual:
              type: number
              format: float
              example: null
              description: The average outturn CO2 emission intensity or carbon intensity for the half hour settlement period with units gCO2-eq/kWh. For future values, this will be null.
            forecast:
              type: number
              format: float
              example: 137.1
              description: The average forecast CO2 emission intensity or carbon intensity for the half hour settlement period with units gCO2-eq/kWh.
            index:
              type: string
              description: How high the emission value is, compared to average. Can be one of "very high", "high", "moderate", "low", or "very low".
              example: "moderate"
    StatisticArray:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/StatisticValue'
    StatisticValue:
      type: object
      properties:
        from:
          type: string
          format: datetime
          example: '2017-09-12 00:30'
          description: The beginning of the requested period. In the format YYYY-MM-DD HH:MM.
        to:
          type: string
          format: datetime
          example: '2017-09-12 01:00'
          description: The beginning of the requested period. In the format YYYY-MM-DD HH:MM.
        intensity:
          type: object
          properties:
            max:
              type: number
              format: float
              example: 292
              description: The maxmimum CO2 emission intensity during the requested period in units of gCO2-eq/kWh. Future periods will use forecast data, past periods will use actual.
            average:
              type: number
              format: float
              example: 218
              description: The average CO2 emission intensity during the requested period in units of gCO2-eq/kWh. Future periods will use forecast data, past periods will use actual.
            min:
              type: number
              format: float
              example: 143
              description: The minimum CO2 emission intensity during the requested period in units of gCO2-eq/kWh. Future periods will use forecast data, past periods will use actual.
            index:
              type: string
              description: How high the average value in this period is, compared to a longer-term average. Can be one of "very high", "high", "moderate", "low", or "very low".
              example: moderate
    ErrorMessage:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: "400 Bad Request"
              description: the HTTP error code produced
            message:
              type: string
              example: "Please enter a valid start and end datetime in ISO8601 format 'YYYY-MM-DDThh:mm'"
